# Generated by Django 4.1.1 on 2022-09-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
