# Generated by Django 4.1.1 on 2022-10-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_brand_slug_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                ("email", models.EmailField(max_length=100)),
                ("review", models.TextField(blank=True)),
                ("star", models.IntegerField(null=True)),
            ],
        ),
    ]
